### ISSUE TITLE
Not working on Ipad and Iphone

### ISSUE THREAD

**Issue by IvMarKon** [BGStock/jquery-background-video#11] opened 2018-06-14 12:12 UTC
Hello, I have an issue with <video> tag removing by itself after page loaded.

**Comment by GusRuss89** [comment] 2018-06-14 22:21
Hi @IvMarKon,

That is the intended behaviour.

> Destroys the video and prevents it downloading on iOS devices (because they can't do background video)

When the plugin was written, iOS didn't work with background videos. It may be different now, but I haven't kept up with the state of iOS and this plugin is further down my priority list than it used to be.

If you want to do some research about support for auto-playing video on new iOS versions and let me know if it's possible to support it properly now then I might be able to update the plugin accordingly.

I'm also open to pull requests.

Thanks,
Angus

**Comment by GusRuss89** [comment] 2018-08-29 22:42
Fixed by #12

**Closed as completed by GusRuss89** 2018-08-29 22:42 UTC
